"""Added new game columns

Revision ID: 59d2d6a7e01f
Revises: 3fea251163bc
Create Date: 2024-10-28 17:33:00.012535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d2d6a7e01f'
down_revision = '3fea251163bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(),
                            nullable=False, server_default='Beginner'))
        batch_op.add_column(sa.Column('trailer', sa.String(), nullable=True))

    # Explicitly update the existing rows to set the correct value for the 'level' column
    op.execute("UPDATE game SET level = 'Beginner' WHERE level IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('trailer')
        batch_op.drop_column('level')
    # ### end Alembic commands ###
